FROM debian:stretch
MAINTAINER Joonun Jang <joonun.jang@gmail.com>

# Install Basic Development Packages
RUN apt-get -y update && apt-get -y install git wget build-essential cmake gcc-multilib g++-multilib gnupg zip autoconf automake libtool docbook2x zlib1g-dev rapidjson-dev apt-transport-https ca-certificates apt-utils vim gnuplot

# Install LLVM Development Package
RUN echo "#LLVM Repository" >> /etc/apt/sources.list && echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-6.0 main" >> /etc/apt/sources.list && echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-6.0 main" >> /etc/apt/sources.list && wget -O ./key.gpg https://apt.llvm.org/llvm-snapshot.gpg.key && apt-key add < ./key.gpg && rm ./key.gpg && apt-get -y update && apt-get -y install clang-6.0 clang-6.0-dev llvm-6.0 llvm-6.0-dev && ln -s /usr/bin/clang-6.0 /usr/bin/clang && ln -s /usr/bin/clang++-6.0 /usr/bin/clang++

# Install AFL
RUN mkdir -p tool && cd /tool && wget http://lcamtuf.coredump.cx/afl/releases/afl-2.52b.tgz && tar zxvf afl-2.52b.tgz && cd /tool/afl-2.52b && make

# Install FuzzBuilder
COPY src/ /fuzzbuilder
RUN mkdir -p /fuzzbuilder/build && cd /fuzzbuilder/build && cmake build .. && make && mv /fuzzbuilder/build/fuzzbuilder /tool/
COPY exp/ /exp/
COPY script/ /tool/

# Install OSS-Fuzz
RUN mkdir -p /exp/oss-fuzz && cd /exp/oss-fuzz && git clone https://github.com/google/oss-fuzz.git source && cd /exp/oss-fuzz/source && git checkout 06b6d9c8b334766112c3b462ea26124b2a5c04ea

# [c-ares]
# 1. Prepare source codes
RUN mkdir -p /exp/c-ares/source && cd /exp/c-ares/source && git clone https://github.com/c-ares/c-ares.git && cd /exp/c-ares/source/c-ares && git checkout c498c5320f9897882989580ecac72c6c11196d73 && cp /exp/c-ares/build.sh /exp/c-ares/source/c-ares && cp /exp/c-ares/afl_driver.cpp /exp/c-ares/source/c-ares && cp /exp/c-ares/fuzzer_main.cc /exp/c-ares/source/c-ares && cp /exp/c-ares/build_libfuzzer.sh /exp/c-ares/source/c-ares && cp /exp/c-ares/build_afl.sh /exp/c-ares/source/c-ares
    
# 2. FuzzBuidler (seed)

RUN cd /exp/c-ares/source/c-ares && rm -f $(find . -name "*.bc") && ./build.sh seed && /tool/afl-2.52b/afl-clang -emit-llvm -DHAVE_CONFIG_H -I. -I. -DCARES_BUILDING_LIBRARY -DCARES_SYMBOL_HIDING -fvisibility=hidden -m32 -Qunused-arguments -g0 -Os -fPIC -DPIC -c ares_create_query.c ares_parse_a_reply.c ares_parse_aaaa_reply.c ares_parse_mx_reply.c ares_parse_naptr_reply.c ares_parse_ns_reply.c ares_parse_ptr_reply.c ares_parse_soa_reply.c ares_parse_srv_reply.c ares_parse_txt_reply.c && /tool/fuzzbuilder seed /exp/c-ares/seed.conf && /tool/afl-2.52b/afl-clang -DHAVE_CONFIG_H -I. -I. -DCARES_BUILDING_LIBRARY -DCARES_SYMBOL_HIDING -fvisibility=hidden -m32 -Qunused-arguments -g0 -Os -fPIC -DPIC -c ares_create_query.bc.mod.bc ares_parse_a_reply.bc.mod.bc ares_parse_aaaa_reply.bc.mod.bc ares_parse_mx_reply.bc.mod.bc ares_parse_naptr_reply.bc.mod.bc ares_parse_ns_reply.bc.mod.bc ares_parse_ptr_reply.bc.mod.bc ares_parse_soa_reply.bc.mod.bc ares_parse_srv_reply.bc.mod.bc ares_parse_txt_reply.bc.mod.bc && mv ares_create_query.bc.mod.o libcares_la-ares_create_query.o && mv ares_parse_a_reply.bc.mod.o libcares_la-ares_parse_a_reply.o && mv ares_parse_aaaa_reply.bc.mod.o libcares_la-ares_parse_aaaa_reply.o && mv ares_parse_mx_reply.bc.mod.o libcares_la-ares_parse_mx_reply.o && mv ares_parse_naptr_reply.bc.mod.o libcares_la-ares_parse_naptr_reply.o && mv ares_parse_ns_reply.bc.mod.o libcares_la-ares_parse_ns_reply.o && mv ares_parse_ptr_reply.bc.mod.o libcares_la-ares_parse_ptr_reply.o && mv ares_parse_soa_reply.bc.mod.o libcares_la-ares_parse_soa_reply.o && mv ares_parse_srv_reply.bc.mod.o libcares_la-ares_parse_srv_reply.o && mv ares_parse_txt_reply.bc.mod.o libcares_la-ares_parse_txt_reply.o && ar r .libs/libcares.a libcares_la-ares_create_query.o libcares_la-ares_parse*.o && cd /exp/c-ares/source/c-ares/test && rm arestest && make && (./arestest || set ?=0) && mv /tmp/fuzzbuilder.collect . && python /tool/seed_maker.py fuzzbuilder.collect seed_fb && mkdir -p /exp/c-ares/seed/fuzzbuilder && mv /exp/c-ares/source/c-ares/test/seed_fb /exp/c-ares/seed/fuzzbuilder/org

# 3. OSS-Fuzz (exec, seed) : AFL

RUN cd /exp/c-ares/source/c-ares && rm -f $(find . -name "*.bc") && ./build.sh && mkdir -p /exp/c-ares/bin/fuzz/oss-fuzz && mkdir -p /exp/c-ares/seed/oss-fuzz/org && mv /exp/c-ares/source/c-ares/*_fuzzer /exp/c-ares/bin/fuzz/oss-fuzz && unzip /exp/c-ares/source/c-ares/ares_create_query_fuzzer_seed_corpus.zip -d /exp/c-ares/seed/oss-fuzz/org/ares_create_query_fuzzer && unzip /exp/c-ares/source/c-ares/ares_parse_reply_fuzzer_seed_corpus.zip -d /exp/c-ares/seed/oss-fuzz/org/ares_parse_reply_fuzzer

# 4. FuzzBuilder (exec)

RUN cd /exp/c-ares/source/c-ares/test && /tool/afl-2.52b/afl-clang++ -emit-llvm -DHAVE_CONFIG_H -I. -I.. -isystem gmock-1.8.0 -m32 -g -Wall -pthread -c ares-test-main.cc ares-test-misc.cc ares-test.cc ares-test-internal.cc dns-proto.cc ares-test-parse-a.cc ares-test-parse.cc ares-test-parse-aaaa.cc ares-test-parse-ptr.cc ares-test-parse-ns.cc ares-test-parse-srv.cc ares-test-parse-txt.cc ares-test-parse-soa.cc ares-test-parse-naptr.cc ares-test-parse-naptr.cc ares-test-parse-mx.cc && /tool/fuzzbuilder exec /exp/c-ares/ares_create_query.conf && /tool/afl-2.52b/afl-clang++ -DHAVE_CONFIG_H -I. -I.. -isystem gmock-1.8.0 -m32 -g -Wall -pthread -c ares-test-main.bc.mod.bc ares-test-misc.bc.mod.bc ares-test.bc.mod.bc ares-test-internal.bc.mod.bc dns-proto.bc.mod.bc && AFL_USE_ASAN=1 /tool/afl-2.52b/afl-clang++ -m32 -Wall -pthread -o ares_create_query_fuzzer ares-test-main.bc.mod.o ares-test-misc.bc.mod.o ares-test.bc.mod.o ares-test-internal.bc.mod.o dns-proto.bc.mod.o .libs/libgmock.a ../.libs/libcares.a && /tool/fuzzbuilder exec /exp/c-ares/ares_parse_reply.conf && /tool/afl-2.52b/afl-clang++ -DHAVE_CONFIG_H -I. -I.. -isystem gmock-1.8.0 -m32 -g -Wall -pthread -c ares-test-main.bc.mod.bc ares-test.bc.mod.bc ares-test-internal.bc.mod.bc dns-proto.bc.mod.bc ares-test-parse-aaaa.bc.mod.bc ares-test-parse-a.bc.mod.bc ares-test-parse.bc.mod.bc ares-test-parse-mx.bc.mod.bc ares-test-parse-naptr.bc.mod.bc ares-test-parse-ns.bc.mod.bc ares-test-parse-ptr.bc.mod.bc ares-test-parse-soa.bc.mod.bc ares-test-parse-srv.bc.mod.bc ares-test-parse-txt.bc.mod.bc && AFL_USE_ASAN=1 /tool/afl-2.52b/afl-clang++ -m32 -g -Wall -pthread -o ares_parse_reply_fuzzer ares-test-main.bc.mod.o ares-test.bc.mod.o ares-test-internal.bc.mod.o dns-proto.bc.mod.o ares-test-parse-aaaa.bc.mod.o ares-test-parse-a.bc.mod.o ares-test-parse.bc.mod.o ares-test-parse-mx.bc.mod.o ares-test-parse-naptr.bc.mod.o ares-test-parse-ns.bc.mod.o ares-test-parse-ptr.bc.mod.o ares-test-parse-soa.bc.mod.o ares-test-parse-srv.bc.mod.o ares-test-parse-txt.bc.mod.o .libs/libgmock.a ../.libs/libcares.a && mkdir -p /exp/c-ares/bin/fuzz/fuzzbuilder && mv /exp/c-ares/source/c-ares/test/*_fuzzer /exp/c-ares/bin/fuzz/fuzzbuilder

# 5. OSS-Fuzz (exec) : libFuzzer
RUN cd /exp/c-ares/source/c-ares && rm -f $(find . -name "*.bc") && ./build_libfuzzer.sh && mv /exp/c-ares/source/c-ares/test/*_libfuzzer /exp/c-ares/bin/fuzz/oss-fuzz

# 6. OSS-Fuzz (exec) : afl
RUN cd /exp/c-ares/source/c-ares && rm -f $(find . -name "*.bc") && ./build_afl.sh && mv /exp/c-ares/source/c-ares/*_afl /exp/c-ares/bin/fuzz/oss-fuzz

# 7. Oss-Fuzz (cov)

RUN cd /exp/c-ares/source/c-ares && rm -f $(find . -name "*.bc") && ./build.sh cov && mkdir -p /exp/c-ares/bin/cov/oss-fuzz && mv /exp/c-ares/source/c-ares/*_fuzzer /exp/c-ares/bin/cov/oss-fuzz

# 8. FuzzBuilder (cov)

RUN cd /exp/c-ares/source/c-ares/test && /tool/afl-2.52b/afl-clang++ -emit-llvm -DHAVE_CONFIG_H -I. -I.. -isystem gmock-1.8.0 -m32 -g -Wall -pthread -c ares-test-main.cc ares-test-misc.cc ares-test.cc ares-test-internal.cc dns-proto.cc ares-test-parse-a.cc ares-test-parse.cc ares-test-parse-aaaa.cc ares-test-parse-ptr.cc ares-test-parse-ns.cc ares-test-parse-srv.cc ares-test-parse-txt.cc ares-test-parse-soa.cc ares-test-parse-naptr.cc ares-test-parse-naptr.cc ares-test-parse-mx.cc &&    /tool/fuzzbuilder exec /exp/c-ares/ares_create_query.conf && /tool/afl-2.52b/afl-clang++ -DHAVE_CONFIG_H -I. -I.. -isystem gmock-1.8.0 -m32 -g -Wall -pthread -c ares-test-main.bc.mod.bc ares-test-main.bc.mod.bc ares-test-misc.bc.mod.bc ares-test.bc.mod.bc ares-test-internal.bc.mod.bc dns-proto.bc.mod.bc && /tool/afl-2.52b/afl-clang++ -fprofile-arcs -ftest-coverage -m32 -Wall -pthread -o ares_create_query_fuzzer ares-test-main.bc.mod.o ares-test-misc.bc.mod.o ares-test.bc.mod.o ares-test-internal.bc.mod.o dns-proto.bc.mod.o .libs/libgmock.a ../.libs/libcares.a && /tool/fuzzbuilder exec /exp/c-ares/ares_parse_reply.conf && /tool/afl-2.52b/afl-clang++ -DHAVE_CONFIG_H -I. -I.. -isystem gmock-1.8.0 -m32 -g -Wall -pthread -c ares-test-main.bc.mod.bc ares-test.bc.mod.bc ares-test-internal.bc.mod.bc dns-proto.bc.mod.bc ares-test-parse-aaaa.bc.mod.bc ares-test-parse-a.bc.mod.bc ares-test-parse.bc.mod.bc ares-test-parse-mx.bc.mod.bc ares-test-parse-naptr.bc.mod.bc ares-test-parse-ns.bc.mod.bc ares-test-parse-ptr.bc.mod.bc ares-test-parse-soa.bc.mod.bc ares-test-parse-srv.bc.mod.bc ares-test-parse-txt.bc.mod.bc && /tool/afl-2.52b/afl-clang++ -fprofile-arcs -ftest-coverage -m32 -g -Wall -pthread -o ares_parse_reply_fuzzer ares-test-main.bc.mod.o ares-test.bc.mod.o ares-test-internal.bc.mod.o dns-proto.bc.mod.o ares-test-parse-aaaa.bc.mod.o ares-test-parse-a.bc.mod.o ares-test-parse.bc.mod.o ares-test-parse-mx.bc.mod.o ares-test-parse-naptr.bc.mod.o ares-test-parse-ns.bc.mod.o ares-test-parse-ptr.bc.mod.o ares-test-parse-soa.bc.mod.o ares-test-parse-srv.bc.mod.o ares-test-parse-txt.bc.mod.o .libs/libgmock.a ../.libs/libcares.a && mkdir -p /exp/c-ares/bin/cov/fuzzbuilder && mv /exp/c-ares/source/c-ares/test/*_fuzzer /exp/c-ares/bin/cov/fuzzbuilder

# 9. Seed Optimization

RUN mkdir -p /exp/c-ares/seed/fuzzbuilder/org/ares_parse_reply && mv /exp/c-ares/seed/fuzzbuilder/org/ares_parse_*_reply/* /exp/c-ares/seed/fuzzbuilder/org/ares_parse_reply && rm -rf /exp/c-ares/seed/fuzzbuilder/org/ares_parse_*_reply && mkdir -p /exp/c-ares/seed/eval/ares_create_query && cd /exp/c-ares/ && /tool/afl-2.52b/afl-cmin -m 1024 -i /exp/c-ares/seed/fuzzbuilder/org/ares_create_query -o /exp/c-ares/seed/eval/ares_create_query/fuzzbuilder /exp/c-ares/bin/fuzz/oss-fuzz/ares_create_query_fuzzer @@ && /tool/afl-2.52b/afl-cmin -m 1024 -i /exp/c-ares/seed/fuzzbuilder/org/ares_parse_reply -o /exp/c-ares/seed/eval/ares_parse_reply/fuzzbuilder /exp/c-ares/bin/fuzz/oss-fuzz/ares_parse_reply_fuzzer @@ && mkdir -p /exp/c-ares/seed/eval/ares_parse_reply &&  /tool/afl-2.52b/afl-cmin -m 1024 -i /exp/c-ares/seed/oss-fuzz/org/ares_create_query_fuzzer -o /exp/c-ares/seed/eval/ares_create_query/oss-fuzz /exp/c-ares/bin/fuzz/oss-fuzz/ares_create_query_fuzzer @@ &&     /tool/afl-2.52b/afl-cmin -m 1024 -i /exp/c-ares/seed/oss-fuzz/org/ares_parse_reply_fuzzer -o /exp/c-ares/seed/eval/ares_parse_reply/oss-fuzz /exp/c-ares/bin/fuzz/oss-fuzz/ares_parse_reply_fuzzer @@ && mkdir -p /exp/c-ares/seed/fuzzbuilder/opt && /tool/afl-2.52b/afl-cmin -m 1024 -i /exp/c-ares/seed/fuzzbuilder/org/ares_create_query -o /exp/c-ares/seed/fuzzbuilder/opt/ares_create_query /exp/c-ares/bin/fuzz/fuzzbuilder/ares_create_query_fuzzer && /tool/afl-2.52b/afl-cmin -m 1024 -i /exp/c-ares/seed/fuzzbuilder/org/ares_parse_reply -o /exp/c-ares/seed/fuzzbuilder/opt/ares_parse_reply /exp/c-ares/bin/fuzz/fuzzbuilder/ares_parse_reply_fuzzer